# Generated by Django 5.1.5 on 2025-02-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("specialization", models.CharField(max_length=200)),
                ("available_slots", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="appointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("timeslot", models.JSONField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ehr.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ehr.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("details", models.TextField()),
                ("date", models.DateField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ehr.patient"
                    ),
                ),
            ],
        ),
    ]
